name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Build and push
      uses: docker/build-push-action@v5
       with:
         push: true
         tags: bacancy-technology/DevOps-Training:latest
         
    - name: 
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
         script: |
         
          # Log in to GitHub Container Registry
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            
          # Check if container is already running
          if docker ps -a --format "{{.Names}}" | grep -q "bacancy-technology-devops-training"; then
             echo "Container is already running, stopping and removing it..."
             docker stop your-container-name
             docker rm your-container-name
             echo "Container stopped and removed."
             echo "Proceeding to pull and run a new container..."
          else
             echo "Container is not running. Proceeding to pull and run a new container..."
          fi          

          # Pull Docker image
          docker pull ghcr.io/bacancy-technology/DevOps-Training:latest

    -     # Run Docker container
          docker run -d -p 80:3000 --name bacancy-technology-devops-training ghcr.io/bacancy-technology/DevOps-Training:latest


